; Generated by ChordLang AsmGenerator
extern init_audio_runtime
extern set_amplitude
extern set_instrument
extern generate_note
extern generate_rest
extern get_buffer_data
extern write_wav_header
extern reset_buffer

section .data
    filename db 'test2.wav', 0
    msg_done db 'Done generating WAV!', 10
    msg_done_len equ $ - msg_done
    freq_0 dd 261.63
    freq_1 dd 392.00

section .bss
    wav_header resb 44
    fd resd 1
    var__t1 resq 1
    var__t3 resq 1
    var__t2 resq 1
    var__t4 resq 1
    var_variation resq 1
    var_counter resq 1
    var__t0 resq 1
    var_repeat_count resq 1

section .text
global _start
_start:
    ; Initialize runtime
    call init_audio_runtime
    ; Program start
    ; repeat_count = 3
    mov rax, 3
    mov qword [var_repeat_count], rax
    ; counter = 0
    mov rax, 0
    mov qword [var_counter], rax
    ; Define chord 'c_major' with 1 notes
    ; Define chord 'g_major' with 1 notes
    ; Define sequence 'verse' with 8 items
    ; Initialize repeat counter to repeat_count
    mov rax, qword [var_repeat_count]
    mov qword [var__t0], rax
    ; Repeat loop start
repeat_start0:
    ; Exit loop if counter is zero
    mov rax, qword [var__t0]
    test rax, rax
    jz repeat_end1
    ; _t1 = counter % 2
    mov rax, qword [var_counter]
    mov rcx, 2
    cqo
    idiv rcx
    mov qword [var__t1], rdx
    ; variation = _t1
    mov rax, qword [var__t1]
    mov qword [var_variation], rax
    ; _t2 = (variation == 0)
    mov rax, qword [var_variation]
    mov rcx, 0
    cmp rax, rcx
    sete al
    movzx rax, al
    mov qword [var__t2], rax
    ; Jump to else if condition is false
    mov rax, qword [var__t2]
    test rax, rax
    jz else2
    ; Play chord 'c_major'
    ; Limitation: Real chords should play all notes at the same time, not sequentially.
    ; However, this runtime only supports single frequency output per note.
    movss xmm0, dword [freq_0]
    mov rdi, 250
    call generate_note
    ; Skip else block
    jmp endif3
    ; Else block
else2:
    ; Play chord 'g_major'
    ; Limitation: Real chords should play all notes at the same time, not sequentially.
    ; However, this runtime only supports single frequency output per note.
    movss xmm0, dword [freq_1]
    mov rdi, 250
    call generate_note
    ; End of if statement
endif3:
    ; _t3 = counter + 1
    mov rax, qword [var_counter]
    mov rcx, 1
    add rax, rcx
    mov qword [var__t3], rax
    ; counter = _t3
    mov rax, qword [var__t3]
    mov qword [var_counter], rax
    ; Decrement counter
    mov rax, qword [var__t0]
    mov rcx, 1
    sub rax, rcx
    mov qword [var__t4], rax
    mov rax, qword [var__t4]
    mov qword [var__t0], rax
    ; Jump back to loop start
    jmp repeat_start0
    ; Repeat loop end
repeat_end1:
    ; Program end
    ; Get buffer data
    call get_buffer_data
    mov r14, rax            ; Save buffer pointer
    mov r15d, edx           ; Save data size

    ; Write WAV header
    mov rdi, wav_header
    mov rsi, r15            ; Data size
    call write_wav_header

    ; Open file
    mov rax, 2              ; sys_open
    mov rdi, filename
    mov rsi, 0x241          ; O_WRONLY | O_CREAT | O_TRUNC
    mov rdx, 0644o
    syscall
    mov [fd], eax

    cmp eax, 0
    jl error_exit

    ; Write WAV header to file
    mov rax, 1              ; sys_write
    mov edi, [fd]
    mov rsi, wav_header
    mov rdx, 44
    syscall

    ; Write audio data to file
    mov rax, 1
    mov edi, [fd]
    mov rsi, r14            ; Buffer pointer
    mov edx, r15d           ; Data size
    syscall

    ; Close file
    mov rax, 3
    mov edi, [fd]
    syscall

    ; Print done message
    mov rax, 1
    mov rdi, 1
    mov rsi, msg_done
    mov rdx, msg_done_len
    syscall

    ; Exit successfully
    mov rax, 60
    xor rdi, rdi
    syscall

error_exit:
    mov rax, 60
    mov rdi, 1
    syscall