; Generated by ChordLang AsmGenerator
extern init_audio_runtime
extern set_amplitude
extern set_instrument
extern generate_note
extern generate_rest
extern get_buffer_data
extern write_wav_header
extern reset_buffer

section .data
    filename db 'output.wav', 0
    msg_done db 'Done generating WAV!', 10
    msg_done_len equ $ - msg_done
    freq_0 dd 261.63
    freq_1 dd 329.63
    freq_2 dd 392.00

section .bss
    wav_header resb 44
    fd resd 1

section .text
global _start
_start:
    ; Initialize runtime
    call init_audio_runtime
    ; Program start
    ; Set tempo to 120
    ; Tempo set to 120 (Informational only)
    ; Set volume to 80
    mov eax, 20640
    cvtsi2ss xmm0, eax
    call set_amplitude
    ; Play note C4
    movss xmm0, dword [freq_0]
    mov rdi, 500
    call generate_note
    ; Play note E4
    movss xmm0, dword [freq_1]
    mov rdi, 500
    call generate_note
    ; Play note G4
    movss xmm0, dword [freq_2]
    mov rdi, 1000
    call generate_note
    ; Program end
    ; Get buffer data
    call get_buffer_data
    mov r14, rax            ; Save buffer pointer
    mov r15d, edx           ; Save data size

    ; Write WAV header
    mov rdi, wav_header
    mov rsi, r15            ; Data size
    call write_wav_header

    ; Open file
    mov rax, 2              ; sys_open
    mov rdi, filename
    mov rsi, 0x241          ; O_WRONLY | O_CREAT | O_TRUNC
    mov rdx, 0644o
    syscall
    mov [fd], eax

    cmp eax, 0
    jl error_exit

    ; Write WAV header to file
    mov rax, 1              ; sys_write
    mov edi, [fd]
    mov rsi, wav_header
    mov rdx, 44
    syscall

    ; Write audio data to file
    mov rax, 1
    mov edi, [fd]
    mov rsi, r14            ; Buffer pointer
    mov edx, r15d           ; Data size
    syscall

    ; Close file
    mov rax, 3
    mov edi, [fd]
    syscall

    ; Print done message
    mov rax, 1
    mov rdi, 1
    mov rsi, msg_done
    mov rdx, msg_done_len
    syscall

    ; Exit successfully
    mov rax, 60
    xor rdi, rdi
    syscall

error_exit:
    mov rax, 60
    mov rdi, 1
    syscall