; Generated by ChordLang AsmGenerator
extern init_audio_runtime
extern set_amplitude
extern set_instrument
extern generate_note
extern generate_rest
extern get_buffer_data
extern write_wav_header
extern reset_buffer

section .data
    filename db 'demo_optimization.wav', 0
    msg_done db 'Done generating WAV!', 10
    msg_done_len equ $ - msg_done
    freq_0 dd 261.63
    freq_1 dd 329.63

section .bss
    wav_header resb 44
    fd resd 1
    var__t2 resq 1
    var__t3 resq 1
    var__t0 resq 1
    var__t1 resq 1
    var__t4 resq 1

section .text
global _start
_start:
    ; Initialize runtime
    call init_audio_runtime
    ; Program start
    ; folded: 60 ADD 60
    mov rax, 120
    mov qword [var__t0], rax
    ; Set tempo to _t0
    ; Tempo set to _t0 (Informational only)
    ; folded: 100 ADD 20
    mov rax, 120
    mov qword [var__t1], rax
    ; Set volume to _t1
    mov eax, dword [var__t1]
    imul eax, 257
    cvtsi2ss xmm0, eax
    call set_amplitude
    ; folded comparison: 1 CMP_GT 0
    mov rax, 1
    mov qword [var__t2], rax
    ; Jump to end if condition is false
    mov rax, qword [var__t2]
    test rax, rax
    jz endif5
    ; folded comparison: 2 CMP_GT 1
    mov rax, 1
    mov qword [var__t3], rax
    ; Jump to end if condition is false
    mov rax, qword [var__t3]
    test rax, rax
    jz endif5
    ; folded comparison: 3 CMP_GT 2
    mov rax, 1
    mov qword [var__t4], rax
    ; Jump to end if condition is false
    mov rax, qword [var__t4]
    test rax, rax
    jz endif5
    ; Play note C4
    movss xmm0, dword [freq_0]
    mov rdi, 500
    call generate_note
    ; End of if statement
endif5:
    ; Play note E4
    movss xmm0, dword [freq_1]
    mov rdi, 500
    call generate_note
    ; Program end
    ; Get buffer data
    call get_buffer_data
    mov r14, rax            ; Save buffer pointer
    mov r15d, edx           ; Save data size

    ; Write WAV header
    mov rdi, wav_header
    mov rsi, r15            ; Data size
    call write_wav_header

    ; Open file
    mov rax, 2              ; sys_open
    mov rdi, filename
    mov rsi, 0x241          ; O_WRONLY | O_CREAT | O_TRUNC
    mov rdx, 0644o
    syscall
    mov [fd], eax

    cmp eax, 0
    jl error_exit

    ; Write WAV header to file
    mov rax, 1              ; sys_write
    mov edi, [fd]
    mov rsi, wav_header
    mov rdx, 44
    syscall

    ; Write audio data to file
    mov rax, 1
    mov edi, [fd]
    mov rsi, r14            ; Buffer pointer
    mov edx, r15d           ; Data size
    syscall

    ; Close file
    mov rax, 3
    mov edi, [fd]
    syscall

    ; Print done message
    mov rax, 1
    mov rdi, 1
    mov rsi, msg_done
    mov rdx, msg_done_len
    syscall

    ; Exit successfully
    mov rax, 60
    xor rdi, rdi
    syscall

error_exit:
    mov rax, 60
    mov rdi, 1
    syscall