; Generated by ChordLang AsmGenerator
extern init_audio_runtime
extern set_amplitude
extern set_instrument
extern generate_note
extern generate_rest
extern get_buffer_data
extern write_wav_header
extern reset_buffer

section .data
    filename db 'demo_music.wav', 0
    msg_done db 'Done generating WAV!', 10
    msg_done_len equ $ - msg_done
    freq_0 dd 261.63
    freq_1 dd 329.63
    freq_2 dd 392.00
    freq_3 dd 523.25
    freq_4 dd 246.94
    freq_5 dd 293.66
    freq_6 dd 493.88
    freq_7 dd 220.00
    freq_8 dd 440.00
    freq_9 dd 196.00
    freq_10 dd 65.41
    freq_11 dd 130.81
    freq_12 dd 49.00
    freq_13 dd 98.00

section .bss
    wav_header resb 44
    fd resd 1
    var__t0 resq 1
    var__t1 resq 1

section .text
global _start
_start:
    ; Initialize runtime
    call init_audio_runtime
    ; Program start
    ; Set tempo to 140
    ; Tempo set to 140 (Informational only)
    ; Set volume to 90
    mov eax, 23220
    cvtsi2ss xmm0, eax
    call set_amplitude
    ; Define sequence 'melody' with 16 items
    ; Define chord 'c_bass' with 2 notes
    ; Define chord 'g_bass' with 2 notes
    ; Set instrument to piano
    mov rdi, 0
    call set_instrument
    ; Initialize repeat counter to 2
    mov rax, 2
    mov qword [var__t0], rax
    ; Repeat loop start
repeat_start0:
    ; Exit loop if counter is zero
    mov rax, qword [var__t0]
    test rax, rax
    jz repeat_end1
    ; Play sequence 'melody'
    movss xmm0, dword [freq_0]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_1]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_2]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_3]
    mov rdi, 500
    call generate_note
    movss xmm0, dword [freq_4]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_5]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_2]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_6]
    mov rdi, 500
    call generate_note
    movss xmm0, dword [freq_7]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_0]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_1]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_8]
    mov rdi, 500
    call generate_note
    movss xmm0, dword [freq_9]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_4]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_5]
    mov rdi, 250
    call generate_note
    movss xmm0, dword [freq_2]
    mov rdi, 500
    call generate_note
    ; Decrement counter
    mov rax, qword [var__t0]
    mov rcx, 1
    sub rax, rcx
    mov qword [var__t1], rax
    mov rax, qword [var__t1]
    mov qword [var__t0], rax
    ; Jump back to loop start
    jmp repeat_start0
    ; Repeat loop end
repeat_end1:
    ; Set instrument to guitar
    mov rdi, 1
    call set_instrument
    ; Set volume to 110
    mov eax, 28380
    cvtsi2ss xmm0, eax
    call set_amplitude
    ; Play note C4
    movss xmm0, dword [freq_0]
    mov rdi, 1000
    call generate_note
    ; Play note E4
    movss xmm0, dword [freq_1]
    mov rdi, 1000
    call generate_note
    ; Play note G4
    movss xmm0, dword [freq_2]
    mov rdi, 1000
    call generate_note
    ; Set instrument to drums_kick
    mov rdi, 5
    call set_instrument
    ; Rest for 0ms
    mov rdi, 0
    call generate_rest
    ; Rest for 500ms
    mov rdi, 500
    call generate_rest
    ; Rest for 0ms
    mov rdi, 0
    call generate_rest
    ; Rest for 500ms
    mov rdi, 500
    call generate_rest
    ; Set instrument to bass
    mov rdi, 2
    call set_instrument
    ; Set volume to 120
    mov eax, 30960
    cvtsi2ss xmm0, eax
    call set_amplitude
    ; Play chord 'c_bass'
    ; Limitation: Real chords should play all notes at the same time, not sequentially.
    ; However, this runtime only supports single frequency output per note.
    movss xmm0, dword [freq_10]
    mov rdi, 1000
    call generate_note
    movss xmm0, dword [freq_11]
    mov rdi, 1000
    call generate_note
    ; Rest for 250ms
    mov rdi, 250
    call generate_rest
    ; Play chord 'g_bass'
    ; Limitation: Real chords should play all notes at the same time, not sequentially.
    ; However, this runtime only supports single frequency output per note.
    movss xmm0, dword [freq_12]
    mov rdi, 1000
    call generate_note
    movss xmm0, dword [freq_13]
    mov rdi, 1000
    call generate_note
    ; Program end
    ; Get buffer data
    call get_buffer_data
    mov r14, rax            ; Save buffer pointer
    mov r15d, edx           ; Save data size

    ; Write WAV header
    mov rdi, wav_header
    mov rsi, r15            ; Data size
    call write_wav_header

    ; Open file
    mov rax, 2              ; sys_open
    mov rdi, filename
    mov rsi, 0x241          ; O_WRONLY | O_CREAT | O_TRUNC
    mov rdx, 0644o
    syscall
    mov [fd], eax

    cmp eax, 0
    jl error_exit

    ; Write WAV header to file
    mov rax, 1              ; sys_write
    mov edi, [fd]
    mov rsi, wav_header
    mov rdx, 44
    syscall

    ; Write audio data to file
    mov rax, 1
    mov edi, [fd]
    mov rsi, r14            ; Buffer pointer
    mov edx, r15d           ; Data size
    syscall

    ; Close file
    mov rax, 3
    mov edi, [fd]
    syscall

    ; Print done message
    mov rax, 1
    mov rdi, 1
    mov rsi, msg_done
    mov rdx, msg_done_len
    syscall

    ; Exit successfully
    mov rax, 60
    xor rdi, rdi
    syscall

error_exit:
    mov rax, 60
    mov rdi, 1
    syscall